name: 'APIM CLI with Docker Hostname Support'
description: 'Execute APIM CLI commands with hostname mapping in Docker container'
inputs:
  command:
    description: 'APIM CLI command to execute'
    required: true
  log_level:
    description: 'Log level for APIM CLI'
    required: false
    default: 'DEBUG'
  port:
    description: 'APIM instance port'
    required: false
    default: '8075'
  apim_ip:
    description: 'APIM instance IP address'
    required: true
  apim_hostname:
    description: 'APIM instance hostname'
    required: true
    default: 'apimgr.lab.demo-latam.axway.com'
outputs:
  exit_code:
    description: 'Exit code from the APIM CLI command'
    value: ${{ steps.apim_cli.outputs.exit_code }}

runs:
  using: 'composite'
  steps:
    - name: Create hosts file for Docker
      id: create_hosts
      shell: bash
      run: |
        echo "🔧 Creating hosts file for Docker container"
        echo "${{ inputs.apim_ip }} ${{ inputs.apim_hostname }}" > /tmp/hosts_apim
        echo "✅ Hosts file created:"
        cat /tmp/hosts_apim

    - name: Execute APIM CLI with hostname mapping
      id: apim_cli
      shell: bash
      run: |
        echo "🔧 Executing APIM CLI with hostname: ${{ inputs.apim_hostname }}"
        echo "🔧 Command: ${{ inputs.command }}"
        
        # Run Docker with custom hosts file
        docker run --rm \
          --add-host="${{ inputs.apim_hostname }}:${{ inputs.apim_ip }}" \
          -e LOG_LEVEL="${{ inputs.log_level }}" \
          -e APIM_PORT="${{ inputs.port }}" \
          -v "${{ github.workspace }}:/workspace" \
          -w /workspace \
          bvieira123/apim-cli:1.14.4 \
          ${{ inputs.command }}
        
        echo "exit_code=$?" >> $GITHUB_OUTPUT
