name: 'Setup Hosts Mapping'
description: 'Add host mapping to /etc/hosts for APIM instance resolution'
inputs:
  apim_ip:
    description: 'IP address of the APIM instance'
    required: true
  apim_hostname:
    description: 'Hostname of the APIM instance'
    required: true
    default: 'apimgr.lab.demo-latam.axway.com'

runs:
  using: 'composite'
  steps:
    - name: Add host mapping to host
      shell: bash
      run: |
        echo "ðŸ”§ Adding host mapping: ${{ inputs.apim_ip }} ${{ inputs.apim_hostname }}"
        echo "${{ inputs.apim_ip }} ${{ inputs.apim_hostname }}" | sudo tee -a /etc/hosts
        echo "âœ… Host mapping added successfully"
        
    - name: Verify host resolution
      shell: bash
      run: |
        echo "ðŸ” Verifying host resolution..."
        if ping -c 1 ${{ inputs.apim_hostname }} > /dev/null 2>&1; then
          echo "âœ… Host ${{ inputs.apim_hostname }} is reachable"
        else
          echo "âš ï¸ Host ${{ inputs.apim_hostname }} is not reachable, but mapping was added"
        fi
        
    - name: Set environment variables for Docker
      shell: bash
      run: |
        echo "ðŸ”§ Setting environment variables for Docker container"
        echo "APIM_HOST_IP=${{ inputs.apim_ip }}" >> $GITHUB_ENV
        echo "APIM_HOST_HOSTNAME=${{ inputs.apim_hostname }}" >> $GITHUB_ENV
        echo "âœ… Environment variables set for Docker container"
