name: 'APIM CLI Action'
description: 'Execute APIM CLI commands using the Axway APIM-CLI GitHub Action'
inputs:
  command:
    description: 'APIM CLI command to execute'
    required: true
  log_level:
    description: 'Log level for APIM CLI'
    required: false
    default: 'DEBUG'
  port:
    description: 'APIM instance port'
    required: false
    default: '8075'
outputs:
  exit_code:
    description: 'Exit code from the APIM CLI command'
    value: ${{ steps.capture_exit_code.outputs.exit_code }}

runs:
  using: 'composite'
  steps:
    - name: Execute APIM CLI command
      id: apim_cli
      continue-on-error: true
      uses: Axway-API-Management-Plus/apim-cli-github-action@v1.14.11
      with:
        command: ${{ inputs.command }}
      env:
        LOG_LEVEL: ${{ inputs.log_level }}
        APIM_PORT: ${{ inputs.port }}
    
    - name: Capture exit code
      id: capture_exit_code
      shell: bash
      run: |
        # Get the real exit code from the Docker container
        # The Axway action runs in Docker, so we need to check the container exit code
        # For now, we'll use outcome but map it properly
        if [ "${{ steps.apim_cli.outcome }}" == "success" ]; then
          echo "exit_code=0" >> $GITHUB_OUTPUT
        else
          # Check if it's a "no changes" scenario by looking at conclusion
          # If conclusion is 'success' but outcome is 'failure', it's likely exit code 10
          if [ "${{ steps.apim_cli.conclusion }}" == "success" ]; then
            echo "exit_code=10" >> $GITHUB_OUTPUT
          else
            echo "exit_code=1" >> $GITHUB_OUTPUT
          fi
        fi
