name: 'APIM CLI Action'
description: 'Execute APIM CLI commands using the Axway APIM-CLI GitHub Action'
inputs:
  command:
    description: 'APIM CLI command to execute'
    required: true
  log_level:
    description: 'Log level for APIM CLI'
    required: false
    default: 'DEBUG'
  port:
    description: 'APIM instance port'
    required: false
    default: '8075'
  apim_ip:
    description: 'APIM instance IP address'
    required: false
  apim_hostname:
    description: 'APIM instance hostname'
    required: false
    default: 'apimgr.lab.demo-latam.axway.com'
outputs:
  exit_code:
    description: 'Exit code from the APIM CLI command'
    value: ${{ steps.apim_cli.outputs.exit_code }}

runs:
  using: 'composite'
  steps:
    - name: Execute APIM CLI command
      id: apim_cli
      uses: Axway-API-Management-Plus/apim-cli-github-action@v1.14.11
      with:
        command: ${{ inputs.command }}
      env:
        LOG_LEVEL: ${{ inputs.log_level }}
        APIM_PORT: ${{ inputs.port }}
