---
name: "API with Custom Properties"
path: "/api-with-custom-props"
state: "published"
version: "1.0"
organization: "API Development"
apiSpecification:
  resource: "../OAS/api-with-custom-props-openapi.json"
vhost: "ec2-18-207-108-191.compute-1.amazonaws.com:8065"
backendBasepath: "http://backend-service:8080"
inboundProfiles:
  _default:
    monitorAPI: true
    queryStringPassThrough: false
    monitorSubject: "authentication.subject.id"
    securityProfile: "_default"
    corsProfile: "_default"
outboundProfiles:
  _default:
    routeType: "proxy"
    authenticationProfile: "_default"
securityProfiles:
- name: "_default"
  isDefault: true
  devices:
  - name: "OAuth"
    type: "oauth"
    order: 1
    properties:
      tokenStore: "OAuth Access Token Store"
      accessTokenLocation: "HEADER"
      authorizationHeaderPrefix: "Bearer"
      scopesMustMatch: "Any"
      scopes: "resource.WRITE, resource.READ"
      removeCredentialsOnSuccess: "true"
      implicitGrantEnabled: "true"
      implicitGrantLoginEndpointUrl: "https://localhost:8089/api/oauth/authorize"
      implicitGrantLoginTokenName: "access_token"
      authCodeGrantTypeEnabled: "true"
      authCodeGrantTypeRequestEndpointUrl: "https://localhost:8089/api/oauth/authorize"
      authCodeGrantTypeRequestClientIdName: "client_id"
      authCodeGrantTypeRequestSecretName: "client_secret"
      authCodeGrantTypeTokenEndpointUrl: "https://localhost:8089/api/oauth/token"
      authCodeGrantTypeTokenEndpointTokenName: "access_code"
      clientCredentialsGrantTypeEnabled: "false"
      clientCredentialsGrantTypeTokenEndpointUrl: "https://localhost:8089/api/oauth/token"
      clientCredentialsGrantTypeTokenName: "access_token"
clientOrganizations:
- "API Development"
- "External Partners"
applications:
- name: "Test Application"
  enabled: true
  state: "approved"
  permissions: []
  appScopes: [] 