name: export-apis
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 1-5'  # Executar às 12:00 BRT (15:00 UTC) em dias úteis
    - cron: '0 21 * * 1-5'  # Executar às 18:00 BRT (21:00 UTC) em dias úteis

jobs:
  export_apis:
    runs-on: ubuntu-latest
    environment: DEMO
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Create export directory
        run: |
          mkdir -p exported-apis

      - name: Export APIs from Axway API Manager
        id: export_apis
        uses: ./.github/actions/apim-cli
        with:
          command: apim api get -h "${{ vars.APIM_INSTANCE_HOSTNAME || 'apimgr.20.253.88.45.nip.io' }}" -u "${{ vars.APIM_INSTANCE_USER }}" -port ${{ vars.APIM_INSTANCE_PORT || '8075' }} -p "${{ secrets.APIM_INSTANCE_PASSWORD }}" -o yaml -t exported-apis
          log_level: DEBUG
          port: ${{ vars.APIM_INSTANCE_PORT || '8075' }}
      
      - name: Handle export result
        run: |
          EXIT_CODE=${{ steps.export_apis.outputs.exit_code }}
          echo "Export completed with exit code: $EXIT_CODE"
          
          # Use intelligent error handling
          source scripts/error-handler.sh
          handle_exit_code $EXIT_CODE "export"
          
          # Exit with the result from error handler
          HANDLER_RESULT=$?
          exit $HANDLER_RESULT

      - name: List exported files
        run: |
          echo "Exported APIs:"
          ls -la exported-apis/
          echo ""
          echo "Contents of each API folder:"
          for dir in exported-apis/*/; do
            if [ -d "$dir" ]; then
              echo "=== $(basename "$dir") ==="
              ls -la "$dir"
              echo ""
            fi
          done

      - name: Upload exported APIs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exported-apis
          path: exported-apis/
          retention-days: 30

      - name: Create summary report
        run: |
          echo "# API Export Summary" > export-summary.md
          echo "Generated on: $(date)" >> export-summary.md
          echo "" >> export-summary.md
          echo "## Exported APIs:" >> export-summary.md
          for dir in exported-apis/*/; do
            if [ -d "$dir" ]; then
              echo "- $(basename "$dir")" >> export-summary.md
            fi
          done
          echo "" >> export-summary.md
          echo "Total APIs exported: $(find exported-apis -maxdepth 1 -type d | wc -l)" >> export-summary.md

      - name: Upload summary report
        uses: actions/upload-artifact@v4
        with:
          name: export-summary
          path: export-summary.md
          retention-days: 30 