name: Manage Organization Permissions
on:
  workflow_call:
    inputs:
      config-file:
        description: "config file for the API"
        type: string
        required: true
      action:
        description: "action to perform (grant or revoke)"
        type: string
        required: true
        default: "grant"
      organization:
        description: "organization name to grant/revoke permissions"
        type: string
        required: true
  workflow_dispatch:
    inputs:
      config-file:
        description: "config file for the API"
        type: string
        required: true
      action:
        description: "action to perform (grant or revoke)"
        type: string
        required: true
        default: "grant"
      organization:
        description: "organization name to grant/revoke permissions"
        type: string
        required: true

jobs:
  manage_permissions:
    runs-on: ubuntu-latest
    environment: DEMO
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      - name: Manage Organization Permissions
        run: |
          echo "Managing organization permissions..."
          echo "Processing ${{ inputs.config-file }} config file"
          config_file_name=$(basename ${{ inputs.config-file }})
          current_folder=$(dirname ${{ inputs.config-file }})
          
          # Extract API name from config file
          if [[ "${{ inputs.config-file }}" == *.yaml ]] || [[ "${{ inputs.config-file }}" == *.yml ]]; then
            # Use yq for YAML files
            API_NAME=$(yq -r '.name' ${{ inputs.config-file }})
          else
            # Use jq for JSON files
            API_NAME=$(jq -r '.name' ${{ inputs.config-file }})
          fi
          echo "API Name: $API_NAME"
          echo "Organization: ${{ inputs.organization }}"
          echo "Action: ${{ inputs.action }}"
          
          # Grant permission to organization
          if [ "${{ inputs.action }}" = "grant" ]; then
            echo "Granting permission to organization ${{ inputs.organization }}..."
            docker run --name apim-cli \
            -e LOG_LEVEL=DEBUG -v "${{ github.workspace }}/${{ inputs.config-file }}:/$config_file_name" \
            bvieira123/apim-cli:1.14.4 \
            apim api grant-access -h ${{ vars.APIM_INSTANCE_IP }} -u ${{ vars.APIM_INSTANCE_USER }} -port ${{ vars.APIM_INSTANCE_PORT || '8075' }} \
            -p ${{ secrets.APIM_INSTANCE_PASSWORD }} -n "$API_NAME" \
            --org "${{ inputs.organization }}"
          fi
          
          # Revoke permission from organization
          if [ "${{ inputs.action }}" = "revoke" ]; then
            echo "Revoking permission from organization ${{ inputs.organization }}..."
            docker run --name apim-cli \
            -e LOG_LEVEL=DEBUG -v "${{ github.workspace }}/${{ inputs.config-file }}:/$config_file_name" \
            bvieira123/apim-cli:1.14.4 \
            apim api revoke-access -h ${{ vars.APIM_INSTANCE_IP }} -u ${{ vars.APIM_INSTANCE_USER }} -port ${{ vars.APIM_INSTANCE_PORT || '8075' }} \
            -p ${{ secrets.APIM_INSTANCE_PASSWORD }} -n "$API_NAME" \
            --org "${{ inputs.organization }}"
          fi
          
          docker rm apim-cli -f
      
      - name: Cleanup
        if: failure()
        run: |
          docker rm apim-cli -f 