name: Setup Environment
on:
  workflow_dispatch:
    inputs:
      org-name:
        description: "Organization name to create"
        type: string
        required: true
        default: "API Development"
      app-name:
        description: "Application name to create"
        type: string
        required: true
        default: "Test Application"
      config-file:
        description: "API config file to deploy (optional)"
        type: string
        required: false
        default: ""
      skip-api:
        description: "Skip API deployment"
        type: boolean
        required: false
        default: false

jobs:
  create_organization:
    runs-on: ubuntu-latest
    environment: DEMO
    steps:
      - name: Create Organization
        run: |
          echo "🏢 Creating organization: ${{ inputs.org-name }}"
          
          docker run --name apim-cli \
          -e LOG_LEVEL=DEBUG \
          bvieira123/apim-cli:1.14.4 \
          apim org create -h "${{ vars.APIM_INSTANCE_IP }}" -u "${{ vars.APIM_INSTANCE_USER }}" -port 8075 \
          -p "${{ secrets.APIM_INSTANCE_PASSWORD }}" \
          --name "${{ inputs.org-name }}" \
          --description "Organization for API Development" \
          --email "admin@apidev.com" \
          --phone "+1234567890" \
          --enabled true \
          --development true
          
          docker rm apim-cli -f
          echo "✅ Organization created successfully!"

  create_application:
    needs: create_organization
    runs-on: ubuntu-latest
    environment: DEMO
    steps:
      - name: Create Application
        run: |
          echo "📱 Creating application: ${{ inputs.app-name }}"
          echo "🏢 Organization: ${{ inputs.org-name }}"
          
          docker run --name apim-cli \
          -e LOG_LEVEL=DEBUG \
          bvieira123/apim-cli:1.14.4 \
          apim app create -h "${{ vars.APIM_INSTANCE_IP }}" -u "${{ vars.APIM_INSTANCE_USER }}" -port 8075 \
          -p "${{ secrets.APIM_INSTANCE_PASSWORD }}" \
          --name "${{ inputs.app-name }}" \
          --org "${{ inputs.org-name }}" \
          --description "Test application for API development" \
          --state "approved" \
          --enabled true \
          --phone "+1234567890" \
          --email "app@apidev.com"
          
          docker rm apim-cli -f
          echo "✅ Application created successfully!"

  deploy_api:
    needs: create_application
    if: inputs.config-file != '' && inputs.skip-api != 'true'
    runs-on: ubuntu-latest
    environment: DEMO
    steps:
      - name: Deploy API
        uses: ./.github/workflows/manual-api-deploy.yaml
        with:
          config-file: ${{ inputs.config-file }}
          force-update: false
        secrets: inherit

  success_summary:
    needs: [create_organization, create_application, deploy_api]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Setup Summary
        run: |
          echo "🎉 Environment setup completed!"
          echo "📋 Summary:"
          echo "  ✅ Organization: ${{ inputs.org-name }}"
          echo "  ✅ Application: ${{ inputs.app-name }}"
          if [ "${{ inputs.config-file }}" != "" ] && [ "${{ inputs.skip-api }}" != "true" ]; then
            echo "  ✅ API: ${{ inputs.config-file }}"
          else
            echo "  ⏭️ API: Skipped"
          fi
          echo ""
          echo "🚀 Next steps:"
          echo "  1. Organizations and applications are ready"
          echo "  2. You can now deploy APIs using manual-api-deploy.yaml"
          echo "  3. Use manage-api-lifecycle.yaml for advanced operations" 