name: Setup Environment
on:
  workflow_dispatch:
    inputs:
      org-name:
        description: "Organization name to create"
        type: string
        required: true
        default: "API Development"
      app-name:
        description: "Application name to create"
        type: string
        required: true
        default: "Test Application"
      config-file:
        description: "API config file to deploy (optional)"
        type: string
        required: false
        default: ""
      skip-api:
        description: "Skip API deployment"
        type: boolean
        required: false
        default: false

jobs:
  create_organization:
    runs-on: ubuntu-latest
    environment: DEMO
    steps:
      - name: Create Organization
        uses: ./.github/actions/apim-cli-with-hostname
        with:
          command: apim org create -h "${{ vars.APIM_INSTANCE_HOSTNAME || 'apimgr.lab.demo-latam.axway.com' }}" -u "${{ vars.APIM_INSTANCE_USER }}" -port ${{ vars.APIM_INSTANCE_PORT || '8075' }} -p "${{ secrets.APIM_INSTANCE_PASSWORD }}" --name "${{ inputs.org-name }}" --description "Organization for API Development" --email "admin@apidev.com" --phone "+1234567890" --enabled true --development true
          log_level: DEBUG
          port: ${{ vars.APIM_INSTANCE_PORT || '8075' }}
          apim_ip: ${{ vars.APIM_INSTANCE_IP }}
          apim_hostname: ${{ vars.APIM_INSTANCE_HOSTNAME || 'apimgr.lab.demo-latam.axway.com' }}

      - name: Organization Creation Result
        run: |
          echo "✅ Organization created successfully!"

  create_application:
    needs: create_organization
    runs-on: ubuntu-latest
    environment: DEMO
    steps:
      - name: Create Application
        uses: ./.github/actions/apim-cli-with-hostname
        with:
          command: apim app create -h "${{ vars.APIM_INSTANCE_HOSTNAME || 'apimgr.lab.demo-latam.axway.com' }}" -u "${{ vars.APIM_INSTANCE_USER }}" -port ${{ vars.APIM_INSTANCE_PORT || '8075' }} -p "${{ secrets.APIM_INSTANCE_PASSWORD }}" --name "${{ inputs.app-name }}" --org "${{ inputs.org-name }}" --description "Test application for API development" --state "approved" --enabled true --phone "+1234567890" --email "app@apidev.com"
          log_level: DEBUG
          port: ${{ vars.APIM_INSTANCE_PORT || '8075' }}
          apim_ip: ${{ vars.APIM_INSTANCE_IP }}
          apim_hostname: ${{ vars.APIM_INSTANCE_HOSTNAME || 'apimgr.lab.demo-latam.axway.com' }}

      - name: Application Creation Result
        run: |
          echo "✅ Application created successfully!"

  deploy_api:
    needs: create_application
    if: inputs.config-file != '' && inputs.skip-api != 'true'
    uses: ./.github/workflows/manual-api-deploy.yaml
    with:
      config-file: ${{ inputs.config-file }}
      force-update: false
    secrets: inherit

  success_summary:
    needs: [create_organization, create_application, deploy_api]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Setup Summary
        run: |
          echo "🎉 Environment setup completed!"
          echo "📋 Summary:"
          echo "  ✅ Organization: ${{ inputs.org-name }}"
          echo "  ✅ Application: ${{ inputs.app-name }}"
          if [ "${{ inputs.config-file }}" != "" ] && [ "${{ inputs.skip-api }}" != "true" ]; then
            echo "  ✅ API: ${{ inputs.config-file }}"
          else
            echo "  ⏭️ API: Skipped"
          fi
          echo ""
          echo "🚀 Next steps:"
          echo "  1. Organizations and applications are ready"
          echo "  2. You can now deploy APIs using manual-api-deploy.yaml"
          echo "  3. Use manage-api-lifecycle.yaml for advanced operations" 